# -*- coding: utf-8 -*-
"""Streamlit app_RetroX

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fxfcb2e7HR7HaBrV6-zV2BK04RK9eOP
"""

!pip install streamlit

# =====================================================
# 🌿 RetroX Toolkit – Full Streamlit Dashboard (Final Version)
# =====================================================
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.express as px
import plotly.graph_objects as go
import shap
import matplotlib.pyplot as plt

# -----------------------------------------------------
# 1️⃣ Fixed building parameters
# -----------------------------------------------------
GFA = 939.62
RoofA, WallA, WinA = 939.62, 397.7, 214.15
total_wall_roof = RoofA + WallA

# -----------------------------------------------------
# 2️⃣ Load trained models
# -----------------------------------------------------
models = {
    'Lighting_kWh': joblib.load('XGB_Lighting_kWh_model.pkl'),
    'Cooling_kWh': joblib.load('RF_Cooling_kWh_model.pkl'),
    'Cooling_Load_kWh': joblib.load('RF_Cooling_Load_kWh_model.pkl')
}

# -----------------------------------------------------
# 3️⃣ Sidebar – Building Inputs
# -----------------------------------------------------
st.sidebar.header("🏗️ Building Inputs")

glazing = st.sidebar.selectbox("Glazing Type", ['Base', 'Double', 'Low-E'])
insul = st.sidebar.selectbox("Insulation", ['Low', 'Med', 'High'])
LPD = st.sidebar.slider("Lighting Power Density (W/m²)", 8.0, 14.0, 10.0)
hvac = st.sidebar.slider("HVAC Setpoint (°C)", 24.0, 27.0, 25.0)
shading = st.sidebar.slider("Shading Depth (m)", 0.25, 1.0, 0.5)
schedule = st.sidebar.radio("Schedule Adjustment", ['No', 'Adjusted'])
ctrl = st.sidebar.radio("Linear Control", [0, 1])
albedo = st.sidebar.radio("High Albedo Wall/Roof", [0, 1])

# -----------------------------------------------------
# 4️⃣ Sidebar – Economic & Environmental Parameters
# -----------------------------------------------------
st.sidebar.header("💰 Tariff & Factors")
tariff = st.sidebar.selectbox("Electricity Tariff (SGD/kWh)",
                              [0.30, 0.35, 0.40])
carbon_factor = st.sidebar.selectbox("Carbon Factor (kg CO₂/kWh)",
                                     [0.40, 0.43, 0.45])

# -----------------------------------------------------
# 5️⃣ Cost formulas (updated High Albedo = wall + roof)
# -----------------------------------------------------
cost_glazing_double = 200 * WinA
cost_glazing_lowe = 300 * WinA
cost_insul_med = 45 * total_wall_roof
cost_insul_high = 55 * total_wall_roof
cost_shading = 120 * WinA
cost_led = 25 * GFA
cost_hvac = 2000
cost_schedule = 1000
cost_albedo = 25 * (RoofA + WallA)  # ✅ corrected formula

# -----------------------------------------------------
# 6️⃣ CAPEX Calculation
# -----------------------------------------------------
CAPEX = 0
if glazing == "Double": CAPEX += cost_glazing_double
elif glazing == "Low-E": CAPEX += cost_glazing_lowe
if insul == "Med": CAPEX += cost_insul_med
elif insul == "High": CAPEX += cost_insul_high
if shading > 0.25: CAPEX += cost_shading
if LPD < 10: CAPEX += cost_led
if hvac > 24: CAPEX += cost_hvac
if schedule == "Adjusted": CAPEX += cost_schedule
if albedo == 1: CAPEX += cost_albedo

# -----------------------------------------------------
# 7️⃣ Input preparation (fix feature mismatch)
# -----------------------------------------------------
feature_names = ['LPD_Wm2', 'HVAC_Setpoint_C', 'ShadingDepth_m',
                 'Glazing_Low-E', 'Glazing_Single',
                 'Insulation_Low', 'Insulation_Medium',
                 'ScheduleAdj_Base', 'LinearControl_Yes',
                 'HighAlbedoWall_Cool']

# Initialize zeros for all features
X_input = pd.DataFrame(np.zeros((1, len(feature_names))), columns=feature_names)

# Assign numeric inputs
X_input['LPD_Wm2'] = LPD
X_input['HVAC_Setpoint_C'] = hvac
X_input['ShadingDepth_m'] = shading

# Assign categorical encodings
X_input['Glazing_Low-E'] = 1 if glazing == 'Low-E' else 0
X_input['Glazing_Single'] = 1 if glazing == 'Base' else 0
X_input['Insulation_Low'] = 1 if insul == 'Low' else 0
X_input['Insulation_Medium'] = 1 if insul == 'Med' else 0
X_input['ScheduleAdj_Base'] = 1 if schedule == 'No' else 0
X_input['LinearControl_Yes'] = 1 if ctrl == 1 else 0
X_input['HighAlbedoWall_Cool'] = 1 if albedo == 1 else 0

# -----------------------------------------------------
# 8️⃣ Model predictions
# -----------------------------------------------------
lighting_pred = models['Lighting_kWh'].predict(X_input)[0]
cooling_pred = models['Cooling_kWh'].predict(X_input)[0]
cool_load_pred = models['Cooling_Load_kWh'].predict(X_input)[0]
room_elec = 31500  # fixed internal load

baseline_energy = 170000
baseline_cool = 97000

# --- KPI calculations ---
total_energy = lighting_pred + cooling_pred + room_elec
energy_saving_pct = (baseline_energy - total_energy) / baseline_energy * 100
EUI = total_energy / GFA
cool_saving_pct = (baseline_cool - cool_load_pred) / baseline_cool * 100
carbon_emission = total_energy * carbon_factor
annual_cost = total_energy * tariff
annual_saving = (baseline_energy - total_energy) * tariff
payback_years = CAPEX / annual_saving if annual_saving > 0 else None

# -----------------------------------------------------
# 9️⃣ KPI Dashboard Tabs
# -----------------------------------------------------
tabs = st.tabs(["⚡ Energy", "🌍 Environment", "💰 Economics"])

with tabs[0]:
    st.subheader("⚡ Energy Performance")
    st.metric("Total Energy (kWh)", f"{total_energy:,.1f}")
    st.metric("Energy Saving (%)", f"{energy_saving_pct:,.1f}%")
    st.metric("EUI (kWh/m²·yr)", f"{EUI:,.2f}")
    st.metric("Cooling Load (kWh)", f"{cool_load_pred:,.1f}")
    st.metric("Cooling Load Saving (%)", f"{cool_saving_pct:,.1f}%")

with tabs[1]:
    st.subheader("🌍 Environmental KPIs")
    st.metric("Carbon Emission (kg CO₂e)", f"{carbon_emission:,.1f}")
    st.metric("Carbon Factor (kgCO₂/kWh)", f"{carbon_factor:,.2f}")

with tabs[2]:
    st.subheader("💰 Economic KPIs")
    st.metric("CAPEX (SGD)", f"{CAPEX:,.0f}")
    st.metric("Annual Cost (SGD)", f"{annual_cost:,.0f}")
    st.metric("Annual Saving (SGD)", f"{annual_saving:,.0f}")
    st.metric("Payback (years)", f"{payback_years:,.1f}")

# -----------------------------------------------------
# 🔍 Interpretation + Green Mark achievement
# -----------------------------------------------------
msg = f"Your building achieves **~{energy_saving_pct:.1f}% energy saving** with a payback of **{payback_years:.1f} years**."
if (EUI < 120) or (energy_saving_pct >= 35):
    msg += " 🏆 **Achieves Green Mark Platinum level.**"
elif (EUI < 135) or (energy_saving_pct >= 30):
    msg += " 🥇 **Achieves Green Mark Gold level.**"
else:
    msg += " 🌱 Meets base efficiency level."
st.info(msg)

# -----------------------------------------------------
# 📄 Download summary CSV
# -----------------------------------------------------
summary = pd.DataFrame({
    'Total_Energy_kWh': [total_energy],
    'Energy_Saving_%': [energy_saving_pct],
    'EUI_kWh_m2': [EUI],
    'Carbon_Emission_kg': [carbon_emission],
    'CAPEX_SGD': [CAPEX],
    'Annual_Saving_SGD': [annual_saving],
    'Payback_Years': [payback_years]
})
csv = summary.to_csv(index=False).encode('utf-8')
st.download_button("📥 Download KPI Summary (CSV)", csv, "RetroX_summary.csv", "text/csv")

# -----------------------------------------------------
# ⚖️ Trade-off Explorer
# -----------------------------------------------------
st.header("⚖️ Trade-off Explorer")
option = st.selectbox("Choose Visualization Type", ["Pareto Front", "2D Contour", "Animated Trade-off"])

if option == "Pareto Front":
    df = pd.DataFrame({
        'Energy_Saving_Percentage': [10,15,20,25,30,35],
        'Payback_Years': [2.5,3.8,5.0,6.8,8.5,10.0],
        'CAPEX_SGD': [10000,15000,25000,40000,60000,80000]
    })
    pareto = df.sort_values('Energy_Saving_Percentage')
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df['Energy_Saving_Percentage'], y=df['Payback_Years'],
                             mode='markers', name='All Scenarios', marker=dict(color='lightgray')))
    fig.add_trace(go.Scatter(x=pareto['Energy_Saving_Percentage'], y=pareto['Payback_Years'],
                             mode='lines+markers', name='Pareto Front', line=dict(color='green', width=3)))
    fig.update_yaxes(autorange='reversed')
    st.plotly_chart(fig, use_container_width=True)

elif option == "2D Contour":
    x = np.linspace(8,14,30)
    y = np.linspace(24,27,30)
    X, Y = np.meshgrid(x, y)
    Z = 180 - (Y-24)*10 - (14-X)*5  # simplified sample relation for EUI
    fig = go.Figure(data=go.Contour(z=Z, x=x, y=y, colorscale='Viridis'))
    fig.update_layout(title="2D Iso-performance Map (EUI vs LPD & HVAC)", xaxis_title="LPD (W/m²)", yaxis_title="HVAC Setpoint (°C)")
    st.plotly_chart(fig, use_container_width=True)

else:
    df_anim = pd.DataFrame({
        'Energy_Saving_%':[10,20,30,35,40,45],
        'Payback_Years':[2,4,6,8,10,12],
        'Scenario':['LED','Envelope','Passive+Active','Deep','Smart','Extreme']
    })
    fig = px.scatter(df_anim, x='Energy_Saving_%', y='Payback_Years', animation_frame='Scenario',
                     size='Energy_Saving_%', color='Scenario', title="Animated Energy–Payback Trade-off")
    fig.update_yaxes(autorange='reversed')
    st.plotly_chart(fig, use_container_width=True)

# -----------------------------------------------------
# 📊 Measure Impact
# -----------------------------------------------------
st.header("📊 Measure Impact")
impact_choice = st.selectbox("Choose Impact Visualization", ["SHAP Bar", "Waterfall", "Radar (Spider)"])

# Example SHAP (dummy)
np.random.seed(42)
features = ['LPD','HVAC','Shading','Insulation','Glazing','Schedule','Albedo']
shap_values = np.abs(np.random.randn(len(features)))
shap_df = pd.DataFrame({'Feature':features, 'Impact':shap_values})

if impact_choice == "SHAP Bar":
    fig = px.bar(shap_df, x='Impact', y='Feature', orientation='h', title="SHAP Feature Importance")
    st.plotly_chart(fig, use_container_width=True)

elif impact_choice == "Waterfall":
    fig = go.Figure(go.Waterfall(
        name="Impact", orientation="v",
        measure=["relative"]*len(features),
        x=features, y=shap_values,
        connector={"line":{"color":"rgb(63, 63, 63)"}}))
    fig.update_layout(title="Feature Contribution to KPI", showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

else:
    categories = features + [features[0]]
    values = list(shap_values) + [shap_values[0]]
    fig = go.Figure(data=go.Scatterpolar(r=values, theta=categories, fill='toself', name='Impact'))
    fig.update_layout(title="Radar Chart of Measure Impacts", polar=dict(radialaxis=dict(visible=True)))
    st.plotly_chart(fig, use_container_width=True)

# Adjustable Impact Index
st.subheader("🎛️ Impact Index Weighting")
w1 = st.slider("Weight for Energy Saving", 0.0, 1.0, 0.5)
w2 = st.slider("Weight for Payback (inverse)", 0.0, 1.0, 0.3)
w3 = st.slider("Weight for CAPEX (inverse)", 0.0, 1.0, 0.2)
impact_index = w1*energy_saving_pct - w2*payback_years - w3*(CAPEX/10000)
st.write(f"Impact Index Score: **{impact_index:.2f}**")

st.success("🌿 RetroX analysis completed successfully.")